### PR TITLE
Partial python 3 compatibility

### PR DESCRIPTION
**Pull request by mpeterv**
There may still be issues with renderer (I do not have Tkinter installed for python 3), but I got rgrun working in headless mode under python 3. I'm quite sure there are better ways to work around some incompatibilities, in particular lack of `long` in python 3(31fdf49), please comment.

### CODE REVIEW

**Comment by mueslo** [comment]
Tkinter works with python3 for me now.

**Comment by mueslo** [comment]
about `long` in 31fdf49: Is anyone really using 'long'? maybe just replace (int, long, float) with (int, float)?

**Comment by mpeterv** [comment]
@mueslo I think that would be fine. I just didn't want to change any behaviour.

**Comment by WhiteHalmos** [comment]
lgtm. Thanks for making the compatibility changes! Once travis is fixed we can add python 3 compatibility to its tests. :)

**Pull request merged**
