### PR TITLE
Upgrade Sphinx and fix python3 compatibility.

### PR DESCRIPTION
**Pull request by WhiteHalmos**
Fix travis build. :)

### CODE REVIEW

**Comment by WhiteHalmos** [comment]
Not waiting for lgtm to unbreak the build.

**Comment by mpeterv** [comment]
Since we now use flake8, pep8-related tests are redundant, right?

**Comment by WhiteHalmos** [comment]
Yep. :)

**Comment by WhiteHalmos** [comment]
Though we probably want to make a test script that combines flake8 with nosetests.

**Pull request merged**
